name: No Duplications

on: [push, pull_request]

jobs:
  nodups:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jscpd
      run: npm install -g jscpd

    - name: Limit complexity
      run: jscpd . --min-lines 3 --min-tokens 48 --threshold 0
